<a href="https://colab.research.google.com/github/jon-vx/neural-net/blob/main/neural_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=8, out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

In [3]:
model = Model()

In [4]:
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
data_frame = pd.read_csv(url)

In [5]:
data_frame

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [6]:
data_frame['variety'] = data_frame['variety'].replace('Setosa', 0.0)
data_frame['variety'] = data_frame['variety'].replace('Versicolor', 1.0)
data_frame['variety'] = data_frame['variety'].replace('Virginica', 2.0)

/tmp/ipython-input-5875/224194209.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_frame['variety'] = data_frame['variety'].replace('Virginica', 2.0)

In [7]:
data_frame.head()

   sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2      0.0
1           4.9          3.0           1.4          0.2      0.0
2           4.7          3.2           1.3          0.2      0.0
3           4.6          3.1           1.5          0.2      0.0
4           5.0          3.6           1.4          0.2      0.0

In [8]:
X = data_frame.drop('variety', axis=1)
y = data_frame['variety']
X = X.values
y = y.values

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

X_train
y_train

tensor([0, 1, 0, 2, 0, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 2, 2, 0, 2, 1, 0,
        2, 2, 0, 1, 0, 2, 2, 2, 0, 1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2,
        2, 2, 2, 2, 1, 0, 1, 1, 1, 1, 2, 0, 2, 1, 0, 2, 1, 0, 2, 1, 1, 2, 1, 0,
        2, 1, 1, 2, 0, 1, 2, 1, 0, 2, 2, 1, 2, 1, 0, 1, 0, 1, 1, 2, 0, 2, 1, 2,
        0, 1, 1, 1, 0, 2, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 1, 0, 1, 1])

In [11]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [12]:
print(model.parameters)

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=8, bias=True)
  (out): Linear(in_features=8, out_features=3, bias=True)
)>

In [13]:
epochs = 100

losses = []

for i in range(epochs):
  y_pred = model.forward(X_train)
  loss = criterion(y_pred, y_train)

  losses.append(loss.detach().numpy())
  if i % 10 == 0:
    print(f'Epoch: {epochs}, Loss: {loss}')

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

Epoch: 100, Loss: 1.1792545318603516
Epoch: 100, Loss: 1.0883761644363403
Epoch: 100, Loss: 1.0227365493774414
Epoch: 100, Loss: 0.8582722544670105
Epoch: 100, Loss: 0.6143138408660889
Epoch: 100, Loss: 0.49030622839927673
Epoch: 100, Loss: 0.4470578730106354
Epoch: 100, Loss: 0.41038942337036133
Epoch: 100, Loss: 0.34852561354637146
Epoch: 100, Loss: 0.26211291551589966